```{r umap clusters}
umap_df <- seurat_obj_sub_5@reductions$umap@cell.embeddings %>%
  as.data.frame() %>% 
  rownames_to_column("cell_id") %>% 
  left_join(seurat_obj_sub_5@meta.data)

clust_labs <- umap_df %>% 
  group_by(SCT_snn_res.0.2) %>% 
  summarise(UMAP_1 = mean(UMAP_1),
            UMAP_2 = mean(UMAP_2))

umap_df %>% 
  ggplot(aes(UMAP_1, UMAP_2))+
  geom_point(aes(color = SCT_snn_res.0.2), size = 0.1)+
  scale_colour_manual(values = cols)+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())+
  coord_fixed()+
  guides(color = FALSE)+ 
  ggsave("umap_clusters.pdf",width =  7, height = 7)
```

```{r umap samples}
umap_df %>% 
  ggplot(aes(UMAP_1, UMAP_2))+
  geom_point(aes(color = orig.ident), size = 0.1)+
  geom_text(data = clust_labs, aes(UMAP_1, UMAP_2, label = SCT_snn_res.0.2), size = 6)+
  scale_colour_manual(values = cols)+
  theme(axis.text = element_blank(),
        axis.ticks = element_blank())+
  coord_fixed()+
  guides(color = FALSE)+
  ggsave("umap_samples_0.2.pdf",width =  7, height = 7)
```

```{r individual cluster percentage,fig.width=10,fig.height=5}
cluster_percent_df <-seurat_obj_sub_5@meta.data %>%
    filter(cell_type %in% relevant_types) %>%
    group_by(orig.ident, SCT_snn_res.0.2) %>%
    summarise(n_cell=n())  %>%
    ungroup() %>% 
    group_by(orig.ident) %>% 
    mutate(freq_cell = n_cell / sum(n_cell),
           individual_n = glue("{orig.ident}\n(n={sum(n_cell)})")) %>%
    ungroup() %>% 
    mutate(orig.ident = factor(orig.ident, levels = c("C1_IKZF2-WT","C2_IKZF2-WT","C3_IKZF2-WT","C4_IKZF2-WT","P_IKZF2-I325V-Hom")))
cluster_percent_df %>% 
    ggplot(aes(x=orig.ident, y=freq_cell, fill = orig.ident, label = glue("{100*round(freq_cell,4)}%")))+
    geom_bar(stat="identity",position = "dodge",show.legend = FALSE)+
    geom_text(size = 2, color = "grey50", angle = 90, hjust  = -0.225)+
    scale_fill_manual(values = cols)+
    scale_y_continuous(limits = c(0,0.7),
                       labels = scales::label_percent())+
    facet_wrap( ~ SCT_snn_res.0.2,ncol = 10)+
    labs(x=NULL, y = "Cell per sample")+
    theme(legend.position = "bottom",
          axis.text.x = element_text(angle = 90))+
    guides(fill = NULL) +
  ggsave("cluster_percent.pdf",width =  10, height = 4)
#save table 
write_csv(cluster_percent_df, "cluster_percent.csv")
```

```{r cluster markers}
#significant markers in 0.75 of comparisons
genes_0.75 <- markers_all_comb %>%
  filter(n_individual/cmps_n >=0.75 ,
         adj_pval < fdr_threshold) %>% 
  group_by(clust) %>% 
  arrange(clust, desc(abs(min_lfc))) %>%
  top_n(15, wt = abs(min_lfc)) %>% 
  ungroup()

#select significant genes and ordered cells 
ph_genes <- genes_0.75$gene
ph_cells <- seurat_obj_sub_5@meta.data %>%
  arrange(SCT_snn_res.0.2) %$%
  cell_id

ph_annot <- list(SCT_snn_res.0.2 = cols[seurat_obj_sub_5@meta.data$SCT_snn_res.0.2 %>%as.character %>%  unique %>% sort],
                 orig.ident = cols[seurat_obj_sub_5@meta.data$orig.ident %>% as.character %>% unique ],
                 Genotype = cols[seurat_obj_sub_5@meta.data$Genotype %>% as.character %>% unique ])

ph_col_annot <- seurat_obj_sub_5@meta.data %>% 
  dplyr::select(orig.ident,Genotype,SCT_snn_res.0.2) %>%
  mutate_if(is.factor, forcats::fct_drop) 

ph_df_scale <- seurat_obj_sub_5@assays$SCT@scale.data[ph_genes, ph_cells]
ph_df_scale[ph_df_scale > 2.5] <- 2.5 #clip values >2.5
ph_df_scale[ph_df_scale < -2.5] <- -2.5 #clip values <-2.5

pheatmap::pheatmap(ph_df_scale,
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   scale = "none",
                   gaps_col = seurat_obj_sub_5@meta.data %>% arrange(SCT_snn_res.0.2)%$% table(SCT_snn_res.0.2) %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                   annotation_col = ph_col_annot,
                   annotation_colors = ph_annot,
                   main = "75% of comparisons: top 15\n",
                   height = 14,
                   width = 9,
                   title = glue("dim(ph_df_scale)[1] genes; dim(ph_df_scale)[2] cells"),
                   filename = "clust_all_markers_complete.png")

pheatmap::pheatmap(ph_df_scale,
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   scale = "none",
                   gaps_col = seurat_obj_sub_5@meta.data %>% arrange(SCT_snn_res.0.2)%$% table(SCT_snn_res.0.2) %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                   show_rownames = FALSE,
                   drop_levels = TRUE,
                   legend = FALSE,
                   annotation_names_col =  FALSE,
                   annotation_names_row = FALSE,
                   annotation_col = ph_col_annot,
                   annotation_colors = ph_annot,
                   main = "75% of comparisons: top 15",
                   height = 14,
                   width = 9,
                   filename = "clust_all_markers_values.png")
```

```{r meta-clusters markers}
#significant markers in 75% of comparisons
genes_0.75 <- markers_meta_all_comb %>%
  filter(!str_sub(gene,start = 1,3) %in% c("RPS","RPL"),
         n_individual/cmps_n >=0.75 & adj_pval < fdr_threshold) %>% 
  mutate(cluster = forcats::fct_relevel(cluster,"meta_0","meta_1"))%>% 
  arrange(cluster,desc(min_lfc)) %>% 
  group_by(cluster) %>% 
  top_n(15, wt = abs(min_lfc))


#select significant genes and ordered cells 
ph_genes <- genes_0.75$gene
ph_cells <- seurat_obj_sub_5@meta.data %>% 
  arrange(meta_cluster,SCT_snn_res.0.2) %$%
  cell_id

ph_annot <- list(meta_cluster =  cols[seurat_obj_sub_5@meta.data$meta_cluster %>%forcats::fct_relevel("meta_0","meta_1") %>% sort()%>% as.character  %>%  unique],
                 SCT_snn_res.0.2 = cols[seurat_obj_sub_5@meta.data$SCT_snn_res.0.2 %>%as.character %>%  unique %>% sort],
                 Genotype = cols[seurat_obj_sub_5@meta.data$Genotype %>% as.character %>% unique ],
                 orig.ident = cols[seurat_obj_sub_5@meta.data$orig.ident %>% as.character %>% unique ])

ph_col_annot <- seurat_obj_sub_5@meta.data %>% 
  dplyr::select(orig.ident,Genotype,SCT_snn_res.0.2,meta_cluster) %>%
  mutate_if(is.factor, forcats::fct_drop)

ph_df_scale <- seurat_obj_sub_5@assays$SCT@scale.data[ph_genes, ph_cells]
ph_df_scale[ph_df_scale > 2.5] <- 2.5 #clip values >2.5
ph_df_scale[ph_df_scale < -2.5] <- -2.5 #clip values <-2.5

pheatmap::pheatmap(ph_df_scale,
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   scale = "none",
                   gaps_col = seurat_obj_sub_5@meta.data %>% arrange(meta_cluster)%$% table(meta_cluster) %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                   annotation_col = ph_col_annot,
                   annotation_colors = ph_annot,
                   main = "75% of comparisons: top 15",
                   height = 12,
                   width = 9,
                   filename = "meta_clust_all_markers_complete.png")

pheatmap::pheatmap(ph_df_scale,
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   scale = "none",
                   gaps_col = seurat_obj_sub_5@meta.data %>% arrange(meta_cluster)%$% table(meta_cluster) %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                   show_rownames = FALSE,
                   drop_levels = TRUE,
                   legend = FALSE,
                   annotation_names_col =  FALSE,
                   annotation_names_row = FALSE,
                   annotation_col = ph_col_annot,
                   annotation_colors = ph_annot,
                   main = "75% of comparisons: top 15",
                   height = 12,
                   width = 9,
                   filename = "meta_clust_all_markers_values.png")
```

```{r }
seur_obj_7_1 <- subset(seurat_obj_sub_5, subset=SCT_snn_res.0.2%in%c("2_a","5"))

ph_genes <- genes_7_1_sig$gene
ph_col_annot <- seur_obj_7_1@meta.data %>% 
  dplyr::select(orig.ident,Genotype,SCT_snn_res.0.2,meta_cluster) %>%
  mutate_if(is.factor, forcats::fct_drop) 

ph_annot <- list(meta_cluster =  cols[seur_obj_7_1@meta.data$meta_cluster %>%forcats::fct_relevel("meta_0","meta_1") %>% sort()%>% as.character  %>%  unique],
                 SCT_snn_res.0.2 = cols[seur_obj_7_1@meta.data$SCT_snn_res.0.2 %>%as.character %>%  unique %>% sort],
                 Genotype = cols[seur_obj_7_1@meta.data$Genotype %>% as.character %>% unique ],
                 orig.ident = cols[seur_obj_7_1@meta.data$orig.ident %>% as.character %>% unique ])

ph_df_scale <- seur_obj_7_1@assays$SCT@scale.data[genes_7_1_sig$gene,]
ph_df_scale[ph_df_scale>2.5] <- 2.5 #clip values >2.5
pheatmap::pheatmap(ph_df_scale,
                   fontsize = 10,
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   cellheight = 9,
                   scale = "none",
                   treeheight_row = 20,
                   cluster_cols = FALSE,
                   show_colnames = FALSE,
                   gaps_col = seur_obj_7_1@meta.data %>% arrange(Genotype) %$% factor(Genotype,levels = c("WT","I325V-Hom")) %>% table() %>% cumsum,
                   annotation_col = ph_col_annot,
                   annotation_colors = ph_annot,
                   height = 6,
                   width = 6,
                   filename = "7_vs_1.pdf")
```


```{r mut vs wt}
#diff genes in each cluster
hm_genes <- diff_genes %>% 
  mutate(reg = ifelse(min_lfc>0, "higher", "lower"),
         clust_reg = paste(cluster, reg, sep = "_")) %>%
  group_by(cluster, reg) %>% 
  arrange(desc(min_lfc)) %>%
  ungroup() %$% 
  split(gene, cluster)

lapply(names(hm_genes), function(cluster_id){
  #subset seurat object that contains one of the clusters
  ser_obj <- subset(seurat_obj_sub_5, subset = SCT_snn_res.0.2 == cluster_id)
  #select genes and cells
  ph_genes <- hm_genes[[cluster_id]]
  ph_cells <- ser_obj@meta.data %>%
    arrange(SCT_snn_res.0.2) %$%
    cell_id

  ph_annot <- list(meta_cluster =  cols[ser_obj@meta.data$meta_cluster %>%forcats::fct_relevel("meta_0","meta_1") %>% sort()%>% as.character  %>%  unique],
                 SCT_snn_res.0.2 = cols[ser_obj@meta.data$SCT_snn_res.0.2 %>%as.character %>%  unique %>% sort],
                 Genotype = cols[seurat_obj_sub_5@meta.data$Genotype %>% as.character %>% unique ],
                 orig.ident = cols[ser_obj@meta.data$orig.ident %>% as.character %>% unique ])

  ph_col_annot <- ser_obj@meta.data[ph_cells,] %>%
    dplyr::select(cell_id,orig.ident,Genotype,SCT_snn_res.0.2,meta_cluster) %>%
    mutate_if(is.factor, forcats::fct_drop) %>% 
    mutate(Genotype = factor(Genotype,levels = c("WT","I325V-Hom"))) %>% 
    column_to_rownames("cell_id")
  
  ph_df_scale <- ser_obj@assays$SCT@scale.data[ph_genes, ph_cells]
  ph_df_scale[ph_df_scale > 2.5] <- 2.5 #clip values >2.5
  ph_df_scale[ph_df_scale < -2.5] <- -2.5 #clip values <-2.5

  pheatmap::pheatmap(ph_df_scale,
                     color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                     scale = "none",
                     gaps_col = ser_obj@meta.data %>% arrange(SCT_snn_res.0.2) %$% factor(Genotype,levels = c("WT","I325V-Hom")) %>% table() %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                     annotation_col = ph_col_annot,
                     annotation_colors = ph_annot,
                     main = cluster_id,
                     filename = glue("diff_mut_wt_{cluster_id}_complete.png")
                     )
  pheatmap::pheatmap(ph_df_scale,
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   scale = "none",
                   gaps_col = ser_obj@meta.data %>% arrange(SCT_snn_res.0.2) %$% factor(Genotype,levels = c("WT","I325V-Hom")) %>% table() %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                   show_rownames = FALSE,
                   drop_levels = TRUE,
                   legend = FALSE,
                   annotation_names_col =  FALSE,
                   annotation_names_row = FALSE,
                   annotation_col = ph_col_annot,
                   annotation_colors = ph_annot,
                   main = cluster_id,
                   filename = glue("diff_mut_wt_{cluster_id}_values.png")
                   )
    pheatmap::pheatmap(ph_df_scale[,1:2],
                   color = colorRampPalette(rev(brewer.pal(7, "PiYG")))(100),
                   scale = "none",
                   #gaps_col = ser_obj@meta.data %>% arrange(SCT_snn_res.0.2) %$% factor(Genotype,levels = c("WT","I325V-Hom")) %>% table() %>% cumsum,
                   cluster_cols = FALSE,
                   cluster_rows = FALSE,
                   show_colnames = FALSE,
                   show_rownames = TRUE,
                   drop_levels = FALSE,
                   legend = TRUE,
                   annotation_names_col =  TRUE,
                   annotation_names_row = TRUE,
                   annotation_col = ph_col_annot[1:2,],
                   annotation_colors = ph_annot,
                   main = cluster_id,
                   filename = glue("diff_mut_wt_{cluster_id}_text.pdf")
                   )
  })
```

